# Generated by Django 4.2.1 on 2023-06-07 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_commune_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveys',
            name='barrio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='surveys.district'),
        ),
        migrations.AddField(
            model_name='surveys',
            name='comuna',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='surveys.commune'),
        ),
    ]
