# Generated by Django 4.2.1 on 2023-06-07 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_surveys_barrio_surveys_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveys',
            name='barrio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.district'),
        ),
        migrations.AlterField(
            model_name='surveys',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.commune'),
        ),
    ]
